### PR TITLE
Remove unused sqlalchemy_helper

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by fblackburn1** [comment]
This helper is still used by wazo-auth and wazo-deployd

**Comment by pc-m** [comment]
Depends-On: https://github.com/wazo-platform/wazo-auth/pull/44

**Comment by sileht** [comment]
Depends-On: https://github.com/TinxHQ/wazo-deployd/pull/6

**Pull request merged**
