### PR TITLE
python 3: Change unicode to str in test

### PR DESCRIPTION
**Pull request by nissou91**
**Why:**
* In python 3, `unicode` check in `isinstance` has been replaced/renamed by `str`.

### CODE REVIEW

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
Please get rid of this code
It's only used by sysconfd

**Comment by fblackburn1** [comment]
I mean get rid of `txtsubst` function
This code date from 2008, it must have something better to do it
Understand why we need it, why it is the only service that need this code and remove or rewrite it directly into sysconfd
hint: to make template use jinja2

**Review by xxbillouxx — APPROVED** [review]
LGTM. Thx

**Comment by xxbillouxx** [comment]
regate

**Review by xxbillouxx — APPROVED** [review]

**Review by xxbillouxx — APPROVED** [review]

**Comment by nissou91** [comment]
> I mean get rid of `txtsubst` function This code date from 2008, it must have something better to do it Understand why we need it, why it is the only service that need this code and remove or rewrite it directly into sysconfd hint: to make template use jinja2 If you are not able to remove it or out of scope. Please create a technical debt ticket to fix it later

Hello, I have removed the code as you suggested and moved it to `wazo-sysconfd`, I will also create a a debt ticket to improve the code later. Can you please check it again now, thanks.

**Review by fblackburn1 — APPROVED** [review]
Please create `fastapi` branch to merge all branch together
* Update JIRA ticket about this new dependency to merge
* base your branch on `fastapi`

**Pull request merged**
