### PR TITLE
WAZO-2505: `lib-python` events

### PR DESCRIPTION
**Pull request by ja0x**
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/59
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/70

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Review by pc-m — DISMISSED** [review]

**Comment by ja0x** [comment]
regate

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Pull request merged**
